# Generated by Django 5.2.11 on 2026-04-07 13:49

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productbatch",
            name="quantity",
        ),
        migrations.AddField(
            model_name="productbatch",
            name="close_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productbatch",
            name="open_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="productbatch",
            name="quantity_produced",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AddField(
            model_name="productbatch",
            name="quantity_sold",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productbatch",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("closed", "Closed")],
                default="open",
                max_length=10,
            ),
        ),
    ]
