# Generated by Django on...
from django.db import migrations
from django.contrib.auth.models import User

def create_superuser(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    
    # Check if superuser already exists
    if not User.objects.filter(is_superuser=True).exists():
        user = User.objects.create_superuser(
            username='Kenani',
            email='gichabakenani@gmail.com',
            password='Onsare@4427'
        )
        user.first_name = 'Kenani'
        user.last_name = 'Gichaba'
        user.save()

def reverse_func(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='Kenani').delete()

class Migration(migrations.Migration):
    dependencies = [
        # Add your dependencies here
        ('accounts', '0001_initial'), 
    ]

    operations = [
        migrations.RunPython(create_superuser, reverse_func),
    ]